site_name: Terracotta Beta
site_url: https://owlfroggy.github.io/terracotta-docs/
docs_dir: docs
theme:
  logo: assets/logo_monochrome.svg
  favicon: assets/logo.svg
  name: material
  custom_dir: overrides
  features:
    # - navigation.sections
    - navigation.path
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.indexes
    - navigation.expand
    - content.code.annotate
    - content.tooltips
  language: en
  palette:
    - scheme: slate
      primary: custom
      accent: deep-orange
markdown_extensions:
  # - codehilite
  - toc:
      permalink: true
      title: Table of Contents
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - abbr
  - attr_list
  - tables
  - attr_list
  - md_in_html
nav:
  - About: index.md
  - Getting Started:
    - Installation Guide: getting_started/installation_guide.md
    - Plot Setup: getting_started/plot_setup.md
    - Language Overview: getting_started/language_overview.md
  - Tools:
    - Action Converter: action_converter.md
  - Code Values:
    - Number: code_values/number.md
    - String: code_values/string.md
    - Styled Text: code_values/styled_text.md
    - List: code_values/list.md
    - Dictionary: code_values/dictionary.md
  - Code Blocks:
    - Event: code_blocks/event.md
    - Function: code_blocks/function.md
    - Process: code_blocks/process.md
    - Action: code_blocks/action.md
    - Set Variable: code_blocks/set_variable.md
    - Control: code_blocks/control.md
    - Select Object: code_blocks/select_object.md
    - If / Else: code_blocks/if.md
    - Repeat (loops): code_blocks/repeat.md
extra_css:
  - style.css
extra_javascript:
  - action_translator.js
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Owlfroggy/terracotta
    - icon: fontawesome/brands/discord
      link: https://discord.gg/at9uBFXPxy
plugins:
  - search
  - table-reader